### ISSUE TITLE
Expose a bin file

### ISSUE THREAD

**Issue by kellyselden** [raszi/node-tmp#181]
Since https://github.com/zkat/npx has come out, it may be convienent to provide a bin file. Then someone can do `npx tmp --dir > ...`.

**Comment by silkentrance** [comment]
Since tmp allows the user to specify arbitrary directories, I am not sure whether this is safe, especially with a user who is trying to lure the 'root' user on either platform into running a task 'nice' which in turn will run 'tmp -dir / --force-cleanup', will begin to cleanup from '/'.

IMO, users should be using os provided mechanisms for creating and managing temporary directories instead of relying on this.

**Comment by silkentrance** [comment]
I am closing this as it poses a potential high security risk.
