### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by missinglink** [raszi/node-tmp#258]
Hi,

I wanted to highlight an issue in how you specify your version number for breaking changes.

The specification adopted by most `npm` modules requires that breaking changes increment the **major** version number.

Recently there have been releases published under the versions `0.2.x` when it should really be `1.x.x`.

This helps downstream consumers better control which updates they accept automatically and which require manual review.

- https://semver.org/
- https://docs.npmjs.com/about-semantic-versioning
- https://blog.npmjs.org/post/162134793605/why-use-semver
- https://semver.npmjs.com/

We were recently affected by this change because we use `https://greenkeeper.io` to automate our dependency updates, Greenkeeper also expected these to be non-breaking changes.

**Comment by raszi** [comment]
Hi @missinglink 

First of all, I am sorry that the recent changes caused issues on your side.

We do understand the how Semantic Versioning is working that is the reason why `tmp` was not moved out from the `0` major version.

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

This does not mean that we aren't planning to stabilize the current package and release the first major version, please see #158

**Comment by missinglink** [comment]
Okay thanks, I've decided to remove this module from our production dependencies but would consider using it again once the API becomes stable.

**Comment by raszi** [comment]
That is of course your decision since it is your codebase.

Although I am not sure I understand your concern. npm handles the version updates correctly if you have a dependency on a package where the major version has not yet reached `1`, then on a minor or a patch version change `npm update` does not update this dependency automatically only if you manually change the version in your `package.json` for the specific package. Therefore breaking changes could only surface with your knowledge.

**Comment by silkentrance** [comment]
@raszi thanks for clearing this up!
